# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    java:
      scanLanguage: "java"
    javascript:
      scanLanguage: "javascript"

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- script: |
    npm -v
    node -v

- script: |
    env
    echo "Running CodeQL for $(scanLanguage)"
    mkdir -p $(Build.StagingDirectory)/codeqldb/$(scanLanguage)
    
    codeql/codeql database create $(Build.StagingDirectory)/codeqldb/$(scanLanguage) \
    --no-run-unnecessary-builds \
    --language=$(scanLanguage)
  displayName: 'CodeQL Database Build for $$(scanLanguage)'




